### ISSUE TITLE
strict mode, octal error

### ISSUE THREAD

**Issue by eugenioclrc** [jeresig/i18n-node-2#92]
When running in strict mode i got a octal error.
Line;
https://github.com/jeresig/i18n-node-2/blob/master/i18n.js#L422

SyntaxError: Octal literals are not allowed in strict mode.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (node_modules/i18n-2/index.js:1:80)

**Comment by gjuchault** [comment]
I was thinking of making an ES2015 version which would fix the issue by using `0o` octal
